# Generated by Django 5.1.3 on 2024-11-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the customer', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the customer', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(help_text='Name of the product ordered', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of the product ordered')),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the order was placed')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount of the order', max_digits=10)),
                ('customer', models.ForeignKey(help_text='The customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.customer')),
            ],
        ),
    ]
